client_config_backend: settings
client_config:
  client_id: 308246707074-npce48feusbqjrgp96bpc2pqskl4g2du.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install